# Generated by Django 2.0.1 on 2018-02-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annonces.Categorie'),
            preserve_default=False,
        ),
    ]
