# Generated by Django 2.0.1 on 2018-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
