# Generated by Django 2.0.1 on 2018-02-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_categorie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='prix',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
