# Generated by Django 2.0.1 on 2018-02-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_annonce_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
