# Generated by Django 2.0.1 on 2018-02-14 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_annonce_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date_publication',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
