# Generated by Django 2.0.1 on 2018-02-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_annonce_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonce',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
